[package]
name = "workbench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi_term = "0.12"
console = "0.15.0"
ctrlc = "3.1.1"
fixed = "1.14"

lib_rgb = { path = "../lib_rgb" }